# import numpy
import nltk
import pandas as pd
import numpy as np
from sklearn import svm, cross_validation
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics import classification_report
from sklearn.cross_validation import train_test_split
from unidecode import unidecode
import re

tfidf_vectorizer = TfidfVectorizer(stop_words=nltk.corpus.stopwords.words('english'), strip_accents='ascii')
count_vectorizer = CountVectorizer(analyzer='word', stop_words=nltk.corpus.stopwords.words('english'), strip_accents='ascii')


lines2 = open('DataSetcategories.txt',encoding = 'utf-8',errors = 'ignore').read().split('\n')
answerWithIndex={}
for line in lines2:
    _line = line.split(' ## ')
    if len(_line)==3:
        #questionWithIndex[int(_line[0])]=_line[1]
        answerWithIndex[int(_line[0])]=_line[2]


def train_svm(data):
  X = extract_features(row[0] for row in data)
  x = [row[1] for row in data]
 
  Y=X[0].toarray()
  
  # clf = svm.LinearSVC()
  clf = svm.SVC(kernel='linear', probability=True)
  clf.fit(X, x)
  return clf

def extract_features(docs):
  docs = map(preprocess_text, docs)
  features = count_vectorizer.fit_transform(docs)
  return features

def preprocess_text(text):
  text = text.lower()
  text = unidecode(text)
  text = remove_rt(text)
  text = remove_twitter_user_mentions(text)
  text = remove_hashtags(text)
  text = remove_links(text)
  text = remove_special_chars(text)
  text = remove_numbers(text)
  # TODO:
  # - remove "kkkkkk"
  return text

def remove_rt(text):
  return re.sub('RT ', '', text)

def remove_twitter_user_mentions(text):
  return re.sub(r'(?:@[\w_]+)', '', text)

def remove_hashtags(text):
  return re.sub(r'(?:\#+[\w_]+[\w\'_\-]*[\w_]+)', '', text)

def remove_links(text):
  return re.sub(r'http\S+', '', text)

def remove_special_chars(text):
  return re.sub(r'[^\w\s\']', '', text)

def remove_numbers(text):
  return re.sub(r'\d', '', text)

def build_classification_report(clf, test_data):
  y_true = [row[1] for row in test_data]
  docs = map(preprocess_text, [row[0] for row in test_data])
  tfidf = count_vectorizer.transform(docs)
  y_pred = clf.predict(tfidf)
  print("predictions########################################")
  #print(y_true)
  print(y_pred)
  print("done#################################################")
  report = classification_report(y_true, y_pred)
  return report

def cross_validation_report(clf, dataset):
  data = count_vectorizer.transform([row[0] for row in dataset])
  target = [row[1] for row in dataset]
  return cross_validation.cross_val_score(clf, data, target)

data = pd.read_csv('Data3.csv', encoding='utf8').as_matrix()
clf = train_svm(data)

sent_1 = "what is the price of an apple in Amazon"
sent_2 = "a Boy is sitting on a table"
sent_3 = "which all organisations are under Amazon?"
sent_4 = "i would like to know about the total number of Amazon's employees"
sent_5 = "give me a description of Amazon"
sent_6 = "How much money did Amazon earn"
sent_7 = "Provide me the details of the total cash generated by Amazon"
sent_8 = "Briefly describe Amazon"
testing_arr=[]
testing_arr.append(sent_1)
testing_arr.append(sent_2)
testing_arr.append(sent_3)
testing_arr.append(sent_4)
testing_arr.append(sent_5)
testing_arr.append(sent_6)
testing_arr.append(sent_7)
testing_arr.append(sent_8)

threshold=0.75

if __name__ == '__main__':
  # numpy.set_printoptions(threshold='nan')
  train_data, test_data = train_test_split(data, test_size=0.2)
  print ('Training SVM...')
  print(train_data)
  clf = train_svm(train_data)
  print ('SVM trained')

  print ('Building reports...')
  print ('Classification report:')
  print (build_classification_report(clf, test_data))
  print ('----------')
  print ('Cross-validation report:')
  print (cross_validation_report(clf, data))
  docs = map(preprocess_text, [row for row in testing_arr])
  tfidf = count_vectorizer.transform(docs)
  y_pred = clf.predict(tfidf)
  print("predictions########################################")
  #print(y_true)
  print(y_pred)
  pred_pro = clf.predict_proba(tfidf)
  n=len(pred_pro)
  for i in range(n):
    print(testing_arr[i])
    index=np.argmax(pred_pro[i])
    if (pred_pro[i][index]>threshold):
      print(answerWithIndex[index])
    else:
      print("can you say that again")
  print("probability$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
  print(pred_pro)
